### ISSUE TITLE
Error when selecting multiple tokens

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-token-visibility#10]
I attempted to select multiple tokens while one was targeted and I got an error that caused the select tool to no longer work

The error is:
```
libWrapper-wrapper.js:513 Uncaught TypeError: Cannot set properties of undefined (setting 'centerPoint')
[Detected 2 packages: tokenvisibility, lib-wrapper]
    at elevatePoints (visibility_range.js:88:24)
    at DetectionModeBasicSight.testVisibilityDetectionMode (visibility_range.js:62:11)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at CanvasVisibility.testVisibility (foundry.js:33435:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.testVisibilityCanvasVisibility (visibility_range.js:47:10)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at get isVisible [as isVisible] (foundry.js:45582:38)
    at CanvasVisibility.restrictVisibility (foundry.js:33358:68)
    at CanvasVisibility.refresh (foundry.js:33340:10)
    at #update (foundry.js:41473:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)
```
The following modules were enabled:
![image](https://user-images.githubusercontent.com/12570777/203671461-9aef5291-81ef-4a83-a233-8e93a0ad0787.png)

![image](https://user-images.githubusercontent.com/12570777/203671487-3bc0af45-e676-4b6f-93c3-27e2e15538f4.png)

This was the selection I made:
![image](https://user-images.githubusercontent.com/12570777/203671510-bb36b1e9-746e-4d4c-a34d-53d713feacf4.png)

These were my settings:
![image](https://user-images.githubusercontent.com/12570777/203671581-0ea32b99-cce8-47ce-865e-9b8ef8838e75.png)
![image](https://user-images.githubusercontent.com/12570777/203671607-8316a3f5-05d9-45e4-932e-af6bb103f0d4.png)
![image](https://user-images.githubusercontent.com/12570777/203671639-fbee4868-f1ed-44d8-8eab-89e9aa6cb13e.png)

**Comment by caewok** [comment]
I have not yet managed to replicate this. But I did add a check in v0.3.3 for whether the tests array has elements, which might fix this specific error. I don't know why the tests array would be empty, so I expect there is some underlying error yet to be discovered. I will leave this open awhile in case anything related comes up.

**Comment by Zamrod** [comment]
I don't have any issues with this anymore.
