### ISSUE TITLE
When Simbul's cover calculator is active errors are thrown

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-token-visibility#11]
I'm getting the following errors while Simbul's Cover Calculator is active but they go away if you disable Alternate Token Visibility:
```
foundry.js:747 TypeError: Cannot set property ignoresCover of #<Token> which has only a getter
[Detected 1 package: simbuls-cover-calculator]
    at CoverCalculator._patchToken (CoverCalculator.js:392:38)
    at CoverCalculator.patch (CoverCalculator.js:176:25)
    at CoverCalculator.register (CoverCalculator.js:16:25)
    at cover-calculator.js:27:49
    at Array.forEach (<anonymous>)
    at Object.fn (cover-calculator.js:27:32)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7870:11)
    at Game._initializeGameView (foundry.js:8964:16)
    at Game._initializeView (foundry.js:8940:21)
    at Game.initialize (foundry.js:7782:16)
```

**Comment by caewok** [comment]
Fixed in v0.3.3. I changed the property name to "ignoresCoverType" to avoid the naming conflict with Simbul's.
