### ISSUE TITLE
Still Canvas Crash on selecting Tokens ....

### ISSUE THREAD

**Issue by R0TEAM** [caewok/fvtt-token-visibility#28]
"Still" as i have write about it on the Issue#4 last comment .... on this error log it was an full foundry freeze after selecting an Token (not always, but on 4 times from 5)...
Now it works better , but get still Cancas Freezes sometimes on select an token
Log : 
`libWrapper-wrapper.js:513 Uncaught TypeError: constrainedTokenBorder.toPolygon is not a function
[Detected 4 packages: tokenvisibility, lib-wrapper, perfect-vision, levels]
    at Area3d._targetWithinLimitedAngleVision (Area3d.js:418:42)
    at Area3d.percentAreaVisible (Area3d.js:435:16)
    at Area3d.hasLOS (Area3d.js:159:33)
    at testLOSArea3d (visibility_los.js:246:17)
    at DetectionModeBasicSight._testLOSDetectionMode (visibility_los.js:138:16)
    at 🎁DetectionMode.prototype._testLOS#0 (libWrapper-wrapper.js:187:52)
    at 🎁DetectionModeBasicSight.prototype._testPoint#perfect-vision (detection-mode.js:160:23)
    at 🎁DetectionModeBasicSight.prototype._testPoint#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:40919:36
    at Array.some (<anonymous>)
    at DetectionModeBasicSight.testVisibility (foundry.js:40919:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionMode.prototype.testVisibility#levels (wrappers.js:170:20)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#perfect-vision (detection-mode.js:140:28)
    at 🎁DetectionModeBasicSight.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at CanvasVisibility.testVisibility (foundry.js:33566:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.testVisibilityCanvasVisibility (visibility_range.js:47:10)
    at CanvasVisibility.visibilityWrapper (wrappers.js:132:25)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at get isVisible [as isVisible] (foundry.js:45865:38)
    at CanvasVisibility.restrictVisibility (foundry.js:33489:68)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CanvasVisibility.prototype.restrictVisibility#perfect-vision (visibility.js:46:20)
    at 🎁CanvasVisibility.prototype.restrictVisibility#0 (libWrapper-wrapper.js:187:52)
    at 🎁CanvasVisibility.prototype.refresh#perfect-vision (visibility.js:392:18)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁CanvasVisibility.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at #update (foundry.js:41683:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)`

**Comment by caewok** [comment]
I think this is fixed in v0.4.0. If still an issue, please feel free to comment.
