### ISSUE TITLE
Canvas freeze with Alternative Token Visibility & Elevated Vision

### ISSUE THREAD

**Issue by ElroTheOnk** [caewok/fvtt-token-visibility#34]
I'm getting the following console error (in Starfinder, if that could be relevant) with minimum modules enabled. Seems to freeze the current canvas. Switching scenes will unfreeze (temporarily, until reselecting a token with vision and moving them again).

Uncaught TypeError: Math.minMax is not a function
[Detected 3 packages: tokenvisibility, lib-wrapper, elevatedvision]
    at Area3d.visionPolygon (Area3d.js:553:24)
    at Area3d.filterSceneObjectsByVisionPolygon (Area3d.js:595:30)
    at Area3d._findBlockingObjects (Area3d.js:987:30)
    at get blockingObjects [as blockingObjects] (Area3d.js:314:46)
    at Area3d.percentAreaVisible (Area3d.js:242:23)
    at Area3d.hasLOS (Area3d.js:229:33)
    at testLOSArea3d (visibility_los.js:287:17)
    at DetectionModeBasicSight._testLOSDetectionMode (visibility_los.js:138:16)
    at 🎁DetectionMode.prototype._testLOS#0 (libWrapper-wrapper.js:187:52)
    at DetectionModeBasicSight._testPoint (foundry.js:41011:16)
    at foundry.js:40919:36
    at Array.some (<anonymous>)
    at DetectionModeBasicSight.testVisibility (foundry.js:40919:18)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at DetectionModeBasicSight.testVisibilityDetectionMode (visibility_range.js:64:10)
    at 🎁DetectionMode.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at CanvasVisibility.testVisibility (foundry.js:33566:39)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at CanvasVisibility.testVisibilityCanvasVisibility (visibility_range.js:47:10)
    at 🎁CanvasVisibility.prototype.testVisibility#0 (libWrapper-wrapper.js:187:52)
    at get isVisible [as isVisible] (foundry.js:45865:38)
    at CanvasVisibility.restrictVisibility (foundry.js:33489:68)
    at CanvasVisibility.refreshCanvasVisibilityShader (vision.js:287:8)
    at 🎁CanvasVisibility.prototype.refresh#0 (libWrapper-wrapper.js:187:52)
    at #update (foundry.js:41683:58)
    at t.emit (ticker.min.mjs:8:622)
    at e.update (ticker.min.mjs:8:3473)
    at _tick (ticker.min.mjs:8:1482)

**Comment by caewok** [comment]
Should be fixed if you update ATV to v0.4.1 and EV to v0.3.2.

**Comment by ElroTheOnk** [comment]
Thanks, with the fix I can confirm I can't immediately replicable with the problem scene from before :)
